[platformio]
src_dir = esp8266_relay

[env:esp12e]
platform = espressif8266
board = esp01_1m
framework = arduino
monitor_speed = 115200
board_build.flash_mode = dout
board_build.ldscript = eagle.flash.1m64.ld
board_upload.maximum_size = 958448
lib_deps =
  knolleary/PubSubClient
  bblanchon/ArduinoJson @ ^6.21.5
