[platformio]
default_envs = heater, washer

[env]
framework = arduino
monitor_speed = 115200
lib_deps =
    bblanchon/ArduinoJson @ 6.21.5
    paulstoffregen/OneWire @ 2.3.8
    milesburton/DallasTemperature @ 3.11.0
build_unflags = -std=gnu++11
build_flags = -std=gnu++17 -Wall -Wextra -D INSTRUMENT_FIRMWARE_VERSION=30003

[env:heater]
platform = espressif8266 @ 4.2.1
board = nodemcuv2
board_build.filesystem = littlefs
board_build.ldscript = eagle.flash.4m1m.ld
build_src_filter = +<heater.cpp>
build_flags = -std=gnu++17 -Wall -Wextra -D INSTRUMENT_FIRMWARE_VERSION=32008 -D INSTRUMENT_VERSION=\"3.2.0-rc9\"
lib_deps =
    ${env.lib_deps}
    adafruit/Adafruit SSD1306 @ 2.5.13
    adafruit/Adafruit GFX Library @ 1.11.11
    adafruit/Adafruit BusIO @ 1.17.0

[env:washer]
platform = espressif32 @ 6.10.0
board = esp32dev
board_build.flash_size = 4MB
board_build.partitions = partitions_4mb.csv
board_build.filesystem = littlefs
build_src_filter = +<washer.cpp>
build_flags = -std=gnu++17 -Wall -Wextra -D INSTRUMENT_FIRMWARE_VERSION=30605 -D INSTRUMENT_VERSION=\"3.6.0-rc5\"
lib_deps =
    ${env.lib_deps}
    gin66/FastAccelStepper @ 0.31.8
